---

- name: Install awscli package
  pip: name=awscli state=present

- name: Create ~/.aws directory
  file:
    state: directory
    path: "{{awscli_user_home_dir}}/.aws"
    owner: "{{awscli_user}}"
    group: "{{awscli_user}}"
    mode: 0775

# region defaults to the 'ec2_region' variable from ec2.py, else 'us-east-1'
- name: Copy .aws/config
  template:
    src: aws_config.j2
    dest: "{{awscli_user_home_dir}}/.aws/config"
    owner: "{{awscli_user}}"
    group: "{{awscli_user}}"
    mode: 0600

- name: Setup awscli command completion
  lineinfile:
    line: complete -C `which aws_completer` aws
    dest: "{{awscli_user_home_dir}}/.profile"
    create: yes
